// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrJnQispdP_T74aC5e52L8X8d9sSrGKSg',
    appId: '1:736622088680:web:f6eb3c18203c3a1456945d',
    messagingSenderId: '736622088680',
    projectId: 'attendance-app-f7648',
    authDomain: 'attendance-app-f7648.firebaseapp.com',
    storageBucket: 'attendance-app-f7648.appspot.com',
    measurementId: 'G-RMPBCGFVS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyiSfRo3YMa-Kj3synq6Lg-N6CK9M2N6o',
    appId: '1:736622088680:android:63af5bc08697c3d756945d',
    messagingSenderId: '736622088680',
    projectId: 'attendance-app-f7648',
    storageBucket: 'attendance-app-f7648.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2fAWPYVxu5rFD5KCukAW-m3Yzpg2jDcc',
    appId: '1:736622088680:ios:116db7636122924b56945d',
    messagingSenderId: '736622088680',
    projectId: 'attendance-app-f7648',
    storageBucket: 'attendance-app-f7648.appspot.com',
    iosBundleId: 'com.example.timeTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2fAWPYVxu5rFD5KCukAW-m3Yzpg2jDcc',
    appId: '1:736622088680:ios:116db7636122924b56945d',
    messagingSenderId: '736622088680',
    projectId: 'attendance-app-f7648',
    storageBucket: 'attendance-app-f7648.appspot.com',
    iosBundleId: 'com.example.timeTrackingApp',
  );
}
